name: itemrec
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=23.3.1
  - setuptools=68.2.2
  - wheel=0.41.2
  - pytorch=2.2.1
  - torchvision=0.17.1
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.4.1
  - jupyter
  - matplotlib
  - seaborn